# Generated by Django 5.2 on 2025-04-04 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', models.TextField(verbose_name='Program İçeriği (HTML)')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Program Başlığı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kaydedilme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaydedilen Program',
                'verbose_name_plural': 'Kaydedilen Programlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
