# Generated by Django 5.2 on 2025-04-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_savedprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprogram',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı mı?'),
        ),
    ]
