# Generated by Django 5.2 on 2025-04-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_savedprogram_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprogram',
            name='exercise_list',
            field=models.TextField(blank=True, null=True, verbose_name='Egzersiz Listesi (Tahmini)'),
        ),
    ]
